-- Migration: 001_create_menus_table
-- Phase-3: Database & Contracts Lock-in
-- Created: 2026-01-17
-- Description: Creates the menus table with JSONB data column and ownership enforcement
-- IMMUTABLE: Do not modify this migration after deployment

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create menus table
CREATE TABLE IF NOT EXISTS menus (
    -- Primary key: UUID generated by default
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Ownership: Links menu to authenticated user (from Supabase Auth)
    -- This is the SOLE source of ownership enforcement
    -- Backend MUST validate user_id matches authenticated user on all operations
    user_id UUID NOT NULL,
    
    -- Menu content: JSONB blob containing the full menu structure
    -- MUST contain "schema_version" field (enforced by contract, not DB)
    -- Structure defined in /contracts/menu.schema.v1.json
    data JSONB NOT NULL,
    
    -- Publication status: Defaults to false (draft)
    -- ONLY human action may set this to true
    -- Backend MUST prevent automatic publishing
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index on user_id for fast ownership lookups
CREATE INDEX IF NOT EXISTS idx_menus_user_id ON menus(user_id);

-- Index on is_published for filtering published menus
CREATE INDEX IF NOT EXISTS idx_menus_is_published ON menus(is_published);

-- Comment on table
COMMENT ON TABLE menus IS 'User-owned menus with JSONB content. Ownership enforced at backend layer.';
COMMENT ON COLUMN menus.user_id IS 'Owner UUID from Supabase Auth. Backend MUST enforce ownership checks.';
COMMENT ON COLUMN menus.data IS 'Menu content as JSONB. Must validate against /contracts/menu.schema.v1.json';
COMMENT ON COLUMN menus.is_published IS 'Publication status. Only human action may set to true.';
